### ISSUE TITLE
"vc4asm: Command not found" when doing step 7, "make" command of MarkerDetector install

### ISSUE THREAD

**Issue by ArchAngel075** [Seneral/MakersVR#1]
Hi,
Getting the following message when doing step 7 of MarkerDetector install :

[  9%] Generating qpu_blob_tiled_min.bin
make[2]: vc4asm: Command not found
make[2]: *** [CMakeFiles/qpu_blob_tiled_min.dir/build.make:61: qpu_blob_tiled_min.bin] Error 127
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/qpu_blob_tiled_min.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

pi-zero, fresh install with git, open-cv, cmake, python installed

**Comment by Seneral** [comment]
The install instructions are incomplete, you also need to build vc4asm once. Just follow the build instructions and install. 
https://github.com/maazl/vc4asm
Sorry about that
